name: Deploy To Server on Main Push.

on:
  push:
    branches: [ main ]

jobs:
 deploy:
  runs-on: ubuntu-latest
  steps:
   - name: Install SSH key
     uses: shimataro/ssh-key-action@v2
     with:
       key: ${{ secrets.SSH_KEY }}
       known_hosts: ${{ secrets.KNOWN_HOST }}
       
   - name: Deploy with rsync
     run: rsync -avz ./dist/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/testing/AgentServer
